/* G4 animatic on the runner: loads animatic.html, saves the storyboard (one frame per §4.3 key, desktop and
   phone), records the fly-through at the PROPOSED steady scroll as MP4 (ffmpeg), saves the plot map, and
   writes anim.json + clearance.md. Clearance, legibility and pacing are review findings, not a gate: the
   job fails only if the page errors or does not finish.
   Usage: node tools/animatic.mjs [pageUrl] [outDir]   (serve the repo root first; needs ffmpeg on PATH) */
import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';

const URL_ = process.argv[2] ?? 'http://127.0.0.1:8000/animatic.html';
const OUT = process.argv[3] ?? 'animatic';
const FPS = 24, BATCH = 12;
await mkdir(OUT, { recursive: true });

const browser = await chromium.launch({
  channel: 'chromium',
  args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'],
});
const page = await (await browser.newContext({ viewport: { width: 1500, height: 1000 } })).newPage();
const errs = [];
page.on('console', m => { if (m.type() === 'error' && !/^Failed to load resource/.test(m.text())) errs.push(m.text().slice(0, 200)); });
page.on('pageerror', e => errs.push('PAGEERR ' + e.message.slice(0, 200)));
page.on('response', s => { if (s.status() >= 400 && !/\/favicon\.ico$/.test(s.url())) errs.push(`HTTP ${s.status()} ${s.url().slice(0, 160)}`); });

const b64 = (u) => Buffer.from(u.split(',')[1], 'base64');
function encode(file, frames) {   // frames: async iterator of JPEG buffers → H.264 MP4
  return new Promise(async (res, rej) => {
    const ff = spawn('ffmpeg', ['-y', '-loglevel', 'error', '-f', 'image2pipe', '-framerate', String(FPS), '-c:v', 'mjpeg', '-i', '-',
      '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-crf', '22', '-preset', 'medium', '-movflags', '+faststart', file], { stdio: ['pipe', 'inherit', 'inherit'] });
    ff.on('error', rej); ff.on('close', c => (c === 0 ? res() : rej(new Error(`ffmpeg exit ${c}`))));
    try { for await (const f of frames) if (!ff.stdin.write(f)) await new Promise(r => ff.stdin.once('drain', r)); ff.stdin.end(); } catch (e) { ff.kill(); rej(e); }
  });
}

let report = null, files = [], videos = [];
const t0 = Date.now();
try {
  await page.goto(URL_, { timeout: 180000, waitUntil: 'commit' });
  await page.waitForFunction(() => window.__anim && window.__anim.ready, null, { timeout: 10 * 60 * 1000, polling: 1000 });
  const st = await page.evaluate(() => ({ failed: !!window.__anim.failed, errors: window.__anim.errors }));
  if (st.failed) throw new Error('page failed: ' + st.errors[0]);
  report = await page.evaluate(() => window.__anim.report);
  const keys = report.keys;
  await writeFile(`${OUT}/plot-map.png`, b64(await page.evaluate(() => window.__anim.plotMap())));
  files.push({ file: 'plot-map.png', cap: 'Plot map (plan): plots, streets, fault building, Core, Cartographer walk, dart flight, both camera paths' });
  for (const vp of ['desk', 'phone']) {
    await page.evaluate(v => window.__anim.setVP(v), vp);
    // storyboard: one frame per key
    for (let i = 0; i < keys.length; i++) {
      const k = keys[i], f = `board-${vp}-${String(i).padStart(2, '0')}-${k.key}.jpg`;
      await writeFile(`${OUT}/${f}`, b64(await page.evaluate(p => window.__anim.shot(p, 'image/jpeg', 0.9), k.p)));
      files.push({ file: f, cap: `${vp === 'desk' ? 'Desktop' : 'Phone'} ${k.key} · p ${k.p.toFixed(2)} · ${k.note}`, vp, key: k.key });
    }
    // fly-through at the steady scroll
    const secs = report.scroll.vh[vp] / report.scroll.vhPerS, N = Math.round(secs * FPS);
    const file = `animatic-${vp}.mp4`;
    async function* frames() {
      for (let i = 0; i < N; i += BATCH) {
        const ps = Array.from({ length: Math.min(BATCH, N - i) }, (_, j) => (i + j) / (N - 1));
        for (const u of await page.evaluate(ps => window.__anim.shots(ps, 'image/jpeg', 0.86), ps)) yield b64(u);
      }
    }
    const v0 = Date.now();
    await encode(`${OUT}/${file}`, frames());
    videos.push({ file, vp, seconds: secs, frames: N, fps: FPS, encodeS: Math.round((Date.now() - v0) / 1000) });
    console.log(`${file}: ${N} frames in ${Math.round((Date.now() - v0) / 1000)} s`);
  }
} catch (e) { errs.push('RUN ' + e.message.slice(0, 300)); }
await browser.close();

/* clearance.md: the §4.4 /docs/clearance.md, generated; reviewed and committed by hand */
const f2 = (v, d = 2) => (Number.isFinite(v) ? v.toFixed(d) : String(v));
let md = '';
if (report) {
  const L = [];
  L.push('# Clearance report (G4, generated by tools/animatic.mjs)', '');
  L.push(`Camera path: js/camera.js (§4.3 keys with the G2 amendments). Grey-box obstacles: city.js plots + fault building, strata.js cliff, paperwall.js tear outline (mirrored from the shader), livingcore.js geometry as a solid of revolution, the Cartographer as a 0.35 capsule on its PROPOSED walk. Sampled every ${report.clearance.desk.step} of p.`, '');
  L.push(`Corridor: radius ${report.corridor.r} from K5 (p ${report.corridor.p0}) to K19 (p ${report.corridor.p1}), solid obstacles only; the ground is reported separately (the walk is at eye height by design).`, '');
  for (const vp of ['desk', 'phone']) {
    const C = report.clearance[vp];
    L.push(`## ${vp === 'desk' ? 'Desktop' : 'Phone'}: ${C.pass ? 'PASS' : 'FAIL'}`, '');
    L.push('| Obstacle | Closest | At p | Segment | Which |', '|---|---|---|---|---|');
    for (const [k, m] of Object.entries(C.min)) L.push(`| ${k} | ${f2(m.d)} | ${f2(m.p, 4)} | ${m.at} | ${m.name} |`);
    L.push('', `Intersections: ${C.intersections.length ? C.intersections.map(i => `${i.name} p ${f2(i.p0, 4)}–${f2(i.p1, 4)} (depth ${f2(-i.d)})`).join('; ') : 'none'}.`);
    L.push('', `Corridor violations: ${C.corridor.length ? C.corridor.map(c => `${c.at} p ${f2(c.p0, 3)}–${f2(c.p1, 3)} min ${f2(c.d)} (${c.name})`).join('; ') : 'none'}.`);
    L.push('', `Look-at gap: min ${f2(C.lookGap.d)} at ${C.lookGap.at}.`, '');
    L.push('| Tear crossing | p | x, y | Opening | Inside | Margin to torn edge |', '|---|---|---|---|---|---|');
    for (const c of C.crossings) L.push(`| ${c.at} | ${f2(c.p, 4)} | ${f2(c.x)}, ${f2(c.y)} | ${f2(c.open)} | ${c.inside && c.open >= 1 ? 'yes' : 'NO'} | ${f2(c.margin)} |`);
    L.push('');
  }
  L.push('## Legibility (§4.1 rule 7)', '', '| Text | Key | Cap | 1440×900 px | Fits | 390×844 px | Fits |', '|---|---|---|---|---|---|---|');
  for (const r of report.legibility) L.push(`| ${r.item} | ${r.key} | ${r.cap} | ${f2(r.desk.px, 1)} ${r.desk.pass ? 'PASS' : 'FAIL'} | ${r.desk.fits ? 'yes' : 'NO'} | ${f2(r.phone.px, 1)} ${r.phone.pass ? 'PASS' : 'FAIL'} | ${r.phone.fits ? 'yes' : 'NO'} |`);
  L.push('', `Printed result title: desktop "${report.result.desk.title.join(' / ')}", phone "${report.result.phone.title.join(' / ')}".`, '');
  for (const vp of ['desk', 'phone']) {
    L.push(`## Pacing, ${vp === 'desk' ? 'desktop' : 'phone'} (${report.scroll.vh[vp]}vh at a PROPOSED ${report.scroll.vhPerS} vh/s)`, '', '| Segment | Seconds | Units/s | Peak turn °/s | FOV °/s | Flag |', '|---|---|---|---|---|---|');
    for (const r of report.pacing[vp]) L.push(`| ${r.seg} | ${f2(r.dur)} | ${f2(r.speed, 1)} | ${f2(r.turn, 0)} | ${f2(r.fovRate, 1)} | ${r.flag} |`);
    L.push('');
  }
  md = L.join('\n') + '\n';
  await writeFile(`${OUT}/clearance.md`, md);
}
const gate = [];
if (!report) gate.push('page did not finish');
if (errs.length) gate.push(`${errs.length} error(s): ${errs[0]}`);
const log = { ok: !!report && !errs.length, seconds: Math.round((Date.now() - t0) / 1000), errs: [...new Set(errs)].slice(0, 5), files, videos, report, gate: gate.join('; ') || null };
await writeFile(`${OUT}/anim.json`, JSON.stringify(log, null, 1));
console.log(JSON.stringify({ gate: log.gate, files: files.length, videos, clearance: report && { desk: report.clearance.desk.pass, phone: report.clearance.phone.pass } }, null, 1));
if (gate.length) { console.log(`::error::Animatic: ${log.gate}`); process.exit(1); }
